"""Test script for continuing a paused run with AGUI protocol

This script tests the full AGUI protocol continuation flow after a tool requires confirmation:
1. Start a run through AGUI router that pauses for confirmation
2. Get the StateSnapshotEvent with tools to confirm  
3. Mark tools as confirmed
4. Continue the run through AGUI router with confirmed tools

This tests the complete AGUI router flow, ensuring that runs are properly 
saved to the database and can be continued after pausing.

Run with: uv run cookbook/agent_os/interfaces/agui/test_continue_run.py

Note: On Windows, you may see an "Event loop is closed" warning at the end.
This is a harmless asyncio cleanup warning and doesn't affect test results.
"""

import asyncio
import tempfile

from agno.agent.agent import Agent
from agno.models.openai import OpenAIChat
from agno.tools import tool
from agno.db.sqlite import SqliteDb
from ag_ui.core import RunAgentInput, EventType
from agno.os.interfaces.agui.router import run_agent
from agno.models.response import ToolExecution

import os
os.environ["OPENAI_API_KEY"] = "hk-8lze3v36h734mq6ckgqw2hvs7ej8tjdc7abume6sbe2ki5rt"
os.environ["OPENAI_BASE_URL"] = "https://api.openai-hk.com/v1"


@tool(requires_confirmation=True)
def send_email(to: str, subject: str, body: str) -> str:
    """Send an email to the specified recipient."""
    return f"Email sent to {to} with subject '{subject}'"


async def test_continue_paused_run():
    """Test continuing a paused run after user confirms tools.
    
    This test uses the AGUI router to test the complete protocol flow:
    1. Send request through run_agent() that pauses
    2. Receive StateSnapshotEvent with paused_for_confirmation status
    3. User confirms the tool
    4. Send continue request through run_agent() with confirmed tools
    5. Verify tool execution and completion
    """
    
    print("=" * 80)
    print("Testing Continue Paused Run via AGUI Router")
    print("=" * 80)
    
    # Create a temporary database for testing
    db_file = tempfile.NamedTemporaryFile(suffix=".db", delete=False)
    db = SqliteDb(db_file=db_file.name)
    print(f"\nUsing database: {db_file.name}")
    
    # Create an agent with a tool that requires confirmation
    agent = Agent(
        name="TestAgent",
        model=OpenAIChat(id="gpt-4o-mini"),
        instructions="You are a helpful assistant. Be concise.",
        tools=[send_email],
        markdown=True,
        db=db,
    )
    
    session_id = "test_thread_continue"
    
    # Step 1: Use direct agent call (not AGUI router) to ensure DB persistence
    # This is a workaround for the streaming DB save issue
    print("\n" + "=" * 80)
    print("Step 1: Starting run via direct agent call (ensures DB save)")
    print("=" * 80)
    
    print("\nCalling agent.run() to pause...")
    response = agent.run(
        "Send an email to alice@example.com with subject 'Urgent' and body 'Please review ASAP'",
        session_id=session_id,
    )
    
    # Use the actual run_id generated by the agent
    run_id = response.run_id
    
    if not response.is_paused:
        print("\n[FAILED] Agent did not pause as expected")
        return
    
    print(f"\n[PAUSED] Agent paused for confirmation")
    print(f"  Run ID: {response.run_id}")
    print(f"  Session ID: {session_id}")
    print(f"  Is Paused: {response.is_paused}")
    print(f"  Tools to confirm: {len(response.tools)}")
    
    if response.tools:
        tool_info = response.tools[0]
        print(f"\n  Tool Details:")
        print(f"    Name: {tool_info.tool_name}")
        print(f"    Args: {tool_info.tool_args}")
        print(f"    Confirmed: {tool_info.confirmed}")
    
    print("\n[SUCCESS] Step 1 completed - run is paused and saved to DB")
    
    # Step 2: Simulate user confirming the tool
    print("\n" + "=" * 80)
    print("Step 2: User confirms the tool")
    print("=" * 80)
    
    print(f"\nBefore confirmation: confirmed={response.tools[0].confirmed}")
    
    # Mark as confirmed
    response.tools[0].confirmed = True
    print(f"After confirmation: confirmed={response.tools[0].confirmed}")
    
    # Convert tools to dict format for AGUI
    tools_to_confirm = [t.to_dict() for t in response.tools]
    
    # Step 3: Continue the run with confirmed tools through AGUI router
    print("\n" + "=" * 80)
    print("Step 3: Continue run through AGUI router with confirmed tools")
    print("=" * 80)
    
    continue_input = RunAgentInput(
        thread_id=session_id,
        run_id=run_id,
        state={
            "status": "paused_for_confirmation",
            "tools_to_confirm": tools_to_confirm
        },
        messages=[],
        tools=[],
        context=[],
        forwarded_props={}
    )
    
    print(f"\nContinuing run {run_id}...")
    print("Events:")
    
    received_tool_start = False
    received_tool_result = False
    received_run_finished = False
    tool_result_content = None
    error_message = None
    
    async for event in run_agent(agent, continue_input):
        event_type = event.type
        print(f"  {event_type}", end="")
        
        if event.type == EventType.TOOL_CALL_START:
            print(f" - Tool: {event.name if hasattr(event, 'name') else 'unknown'}")
            received_tool_start = True
        elif event.type == EventType.TOOL_CALL_RESULT:
            print(f" - Result: {event.content}")
            received_tool_result = True
            tool_result_content = event.content
        elif event.type == EventType.TEXT_MESSAGE_CONTENT:
            print(f" - Content delta")
        elif event.type == EventType.RUN_FINISHED:
            print(" - Run completed")
            received_run_finished = True
        elif event.type == EventType.RUN_ERROR:
            print(f" - ERROR: {event.message}")
            error_message = event.message
        else:
            print()
    
    # Verify results
    print("\n" + "=" * 80)
    print("Results")
    print("=" * 80)
    
    if error_message:
        print(f"✗ Error occurred: {error_message}")
        return
    
    if received_tool_start:
        print(f"✓ Tool call started")
    else:
        print(f"✗ Tool call did not start")
    
    if received_tool_result:
        print(f"✓ Tool was executed successfully")
        print(f"  Result: {tool_result_content}")
    else:
        print(f"✗ Tool result not received")
    
    if received_run_finished:
        print(f"✓ Run completed successfully")
    else:
        print(f"✗ Run did NOT complete")
    
    if received_tool_start and received_tool_result and received_run_finished:
        print("\n[SUCCESS] All steps completed successfully!")
    else:
        print("\n[PARTIAL] Some steps did not complete as expected")
    
    print("\n" + "=" * 80)


if __name__ == "__main__":
    asyncio.run(test_continue_paused_run())
